services:
  - type: web
    name: 19s-hub-trial
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: KEYAUTH_NAME
        sync: false
      - key: KEYAUTH_OWNER_ID
        sync: false